---
# task file for 'deploy from scratch' postgres
- name: "apt installation"
  apt:
    update_cache: yes
    name:
      - "acl"
      - "postgresql"
      - "python3-pip"
      - "python3-dev"
      - "python3-psycopg2"
      - "libpq-dev"
      - "build-essential"
    state: "present"
  become: true

- name: "start postgres service"
  service:
    name: "postgresql"
    state: "started"
    enabled: yes
  become: true

- name: "Create user with specific right"
  postgresql_user:
    name: "{{postgres_user}}"
    password: "{{postgres_password}}"
    role_attr_flags: SUPERUSER
  become_user: "postgres"
  become: true

- name: "Grant user on the DB"
  postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: local
    users: "{{postgres_user}}"
    databases: "all"
    method: md5
    create: true
  become_user: "postgres"
  become: true
