---
# task file for 'deploy from scratch' postgres
- name: "apt installation"
  apt:
    update_cache: true
    name:
      - "acl"
      - "postgresql"
      - "python3-pip"
      - "python3-dev"
      - "python3-psycopg2"
      - "libpq-dev"
      - "build-essential"
    state: "present"
  become: true

- name: "start postgres service"
  service:
    name: "postgresql"
    state: "started"
    enabled: true
  become: true
